### ISSUE TITLE
项目很赞，有没有兴趣来阿里的前端团队

### ISSUE THREAD

**Issue by xiamidaxia** [alex1504/PetalFM#1]
你好，我这边是杭州阿里支付宝商家组的前端团队，我们团队正在打造一个前端基础研发体系，会涉及大量的工具制作，包括web-ide, ui自动化测试等，也是基于react技术, 有兴趣可以关注我们团队leader的这篇文章：https://zhuanlan.zhihu.com/p/34790596

如果觉得不错的话，可以联系我的个人邮箱: xiamidaxia@icloud.com

**Comment by alex1504** [comment]
谢谢邀请，目前可能只考虑深圳的岗位
